import {
  User,
  Company,
  Doctor,
  Shop,
  Product,
  Visit,
  Task,
  Attendance,
  DailyExplanation,
  Expense,
  DashboardMetrics,
  MRDashboardMetrics,
  ChartDataPoint,
} from '@/types';

// Demo Company
export const demoCompany: Company = {
  id: 'comp-001',
  name: 'Riddhi Life Sciences',
  logo: undefined,
  themeColor: '#2563EB',
  address: '123 Pharma District, Mumbai, Maharashtra 400001',
  phone: '+91 22 1234 5678',
  email: 'info@riddhilifesciences.com',
};

// Users
export const mockUsers: User[] = [
  {
    id: 'user-001',
    username: 'admin',
    name: 'Rajesh Kumar',
    role: 'admin',
    companyId: 'comp-001',
    headquarters: 'Mumbai',
    email: 'rajesh@riddhilifesciences.com',
    phone: '+91 98765 43210',
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'user-002',
    username: 'mr_amit',
    name: 'Amit Sharma',
    role: 'mr',
    companyId: 'comp-001',
    headquarters: 'Mumbai Central',
    email: 'amit@riddhilifesciences.com',
    phone: '+91 98765 43211',
    isActive: true,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'user-003',
    username: 'mr_priya',
    name: 'Priya Patel',
    role: 'mr',
    companyId: 'comp-001',
    headquarters: 'Andheri',
    email: 'priya@riddhilifesciences.com',
    phone: '+91 98765 43212',
    isActive: true,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'user-004',
    username: 'mr_vikram',
    name: 'Vikram Singh',
    role: 'mr',
    companyId: 'comp-001',
    headquarters: 'Thane',
    email: 'vikram@riddhilifesciences.com',
    phone: '+91 98765 43213',
    isActive: true,
    createdAt: '2024-02-15T00:00:00Z',
  },
  {
    id: 'user-005',
    username: 'mr_neha',
    name: 'Neha Gupta',
    role: 'mr',
    companyId: 'comp-001',
    headquarters: 'Bandra',
    email: 'neha@riddhilifesciences.com',
    phone: '+91 98765 43214',
    isActive: true,
    createdAt: '2024-03-01T00:00:00Z',
  },
];

// Doctors
export const mockDoctors: Doctor[] = [
  {
    id: 'doc-001',
    name: 'Dr. Anil Mehta',
    specialization: 'General Physician',
    qualification: 'MBBS, MD',
    town: 'Andheri West',
    headquarters: 'Mumbai Central',
    address: '45 Medical Plaza, Andheri West, Mumbai',
    phone: '+91 98765 11111',
    visitFrequency: { thisWeek: 2, thisMonth: 8 },
    lastVisit: '2025-01-04T10:30:00Z',
    coordinates: { lat: 19.1364, lng: 72.8296 },
    businessEntry: 45000,
    companyId: 'comp-001',
  },
  {
    id: 'doc-002',
    name: 'Dr. Sunita Rao',
    specialization: 'Cardiologist',
    qualification: 'MBBS, DM Cardiology',
    town: 'Bandra',
    headquarters: 'Bandra',
    address: '78 Heart Care Center, Bandra, Mumbai',
    phone: '+91 98765 22222',
    visitFrequency: { thisWeek: 1, thisMonth: 5 },
    lastVisit: '2025-01-03T14:00:00Z',
    coordinates: { lat: 19.0596, lng: 72.8295 },
    businessEntry: 78000,
    companyId: 'comp-001',
  },
  {
    id: 'doc-003',
    name: 'Dr. Ramesh Iyer',
    specialization: 'Orthopedic',
    qualification: 'MBBS, MS Ortho',
    town: 'Dadar',
    headquarters: 'Mumbai Central',
    address: '23 Bone & Joint Clinic, Dadar, Mumbai',
    phone: '+91 98765 33333',
    visitFrequency: { thisWeek: 3, thisMonth: 10 },
    lastVisit: '2025-01-05T09:00:00Z',
    coordinates: { lat: 19.0178, lng: 72.8478 },
    businessEntry: 56000,
    companyId: 'comp-001',
  },
  {
    id: 'doc-004',
    name: 'Dr. Kavita Shah',
    specialization: 'Dermatologist',
    qualification: 'MBBS, MD Dermatology',
    town: 'Juhu',
    headquarters: 'Andheri',
    address: '112 Skin Care Clinic, Juhu, Mumbai',
    phone: '+91 98765 44444',
    visitFrequency: { thisWeek: 0, thisMonth: 3 },
    lastVisit: '2024-12-28T11:30:00Z',
    coordinates: { lat: 19.1075, lng: 72.8263 },
    businessEntry: 34000,
    companyId: 'comp-001',
  },
  {
    id: 'doc-005',
    name: 'Dr. Prakash Desai',
    specialization: 'Pediatrician',
    qualification: 'MBBS, DCH',
    town: 'Thane',
    headquarters: 'Thane',
    address: '56 Child Care Hospital, Thane',
    phone: '+91 98765 55555',
    visitFrequency: { thisWeek: 2, thisMonth: 7 },
    lastVisit: '2025-01-04T16:00:00Z',
    coordinates: { lat: 19.2183, lng: 72.9781 },
    businessEntry: 42000,
    companyId: 'comp-001',
  },
  {
    id: 'doc-006',
    name: 'Dr. Meena Kulkarni',
    specialization: 'Gynecologist',
    qualification: 'MBBS, DGO',
    town: 'Chembur',
    headquarters: 'Mumbai Central',
    address: '89 Women Care Center, Chembur, Mumbai',
    phone: '+91 98765 66666',
    visitFrequency: { thisWeek: 1, thisMonth: 4 },
    lastVisit: '2025-01-02T13:00:00Z',
    coordinates: { lat: 19.0522, lng: 72.9005 },
    businessEntry: 52000,
    companyId: 'comp-001',
  },
];

// Shops
export const mockShops: Shop[] = [
  {
    id: 'shop-001',
    name: 'MedPlus Pharmacy',
    address: '12 Main Road, Andheri East, Mumbai',
    town: 'Andheri',
    phone: '+91 22 3456 7890',
    contactPerson: 'Suresh Patil',
    coordinates: { lat: 19.1197, lng: 72.8464 },
    companyId: 'comp-001',
  },
  {
    id: 'shop-002',
    name: 'Apollo Pharmacy',
    address: '34 Station Road, Bandra, Mumbai',
    town: 'Bandra',
    phone: '+91 22 3456 7891',
    contactPerson: 'Rohit Verma',
    coordinates: { lat: 19.0544, lng: 72.8402 },
    companyId: 'comp-001',
  },
  {
    id: 'shop-003',
    name: 'Wellness Forever',
    address: '67 Hill Road, Thane',
    town: 'Thane',
    phone: '+91 22 3456 7892',
    contactPerson: 'Anita Joshi',
    coordinates: { lat: 19.2094, lng: 72.9631 },
    companyId: 'comp-001',
  },
];

// Products
export const mockProducts: Product[] = [
  {
    id: 'prod-001',
    name: 'CardioMax 50mg',
    category: 'Cardiovascular',
    description: 'Blood pressure management tablet',
    targetFrequency: 10,
    price: 450,
    sku: 'CM-050',
    isActive: true,
    companyId: 'comp-001',
  },
  {
    id: 'prod-002',
    name: 'DiabeCare 500mg',
    category: 'Diabetes',
    description: 'Glucose control medication',
    targetFrequency: 15,
    price: 320,
    sku: 'DC-500',
    isActive: true,
    companyId: 'comp-001',
  },
  {
    id: 'prod-003',
    name: 'BoneStrong Plus',
    category: 'Orthopedic',
    description: 'Calcium and Vitamin D supplement',
    targetFrequency: 12,
    price: 280,
    sku: 'BS-001',
    isActive: true,
    companyId: 'comp-001',
  },
  {
    id: 'prod-004',
    name: 'SkinGlow Cream',
    category: 'Dermatology',
    description: 'Moisturizing skin cream',
    targetFrequency: 8,
    price: 180,
    sku: 'SG-001',
    isActive: true,
    companyId: 'comp-001',
  },
  {
    id: 'prod-005',
    name: 'PediaVit Syrup',
    category: 'Pediatric',
    description: 'Multivitamin syrup for children',
    targetFrequency: 10,
    price: 150,
    sku: 'PV-001',
    isActive: true,
    companyId: 'comp-001',
  },
  {
    id: 'prod-006',
    name: 'FemCare 250mg',
    category: 'Gynecology',
    description: 'Women health supplement',
    targetFrequency: 8,
    price: 390,
    sku: 'FC-250',
    isActive: true,
    companyId: 'comp-001',
  },
];

// Today's date helpers
const today = new Date();
const formatDate = (date: Date) => date.toISOString().split('T')[0];

// Visits
export const mockVisits: Visit[] = [
  {
    id: 'visit-001',
    type: 'doctor',
    mrId: 'user-002',
    mrName: 'Amit Sharma',
    doctorId: 'doc-001',
    doctorName: 'Dr. Anil Mehta',
    timestamp: `${formatDate(today)}T09:30:00Z`,
    coordinates: { lat: 19.1364, lng: 72.8296 },
    notes: 'Discussed CardioMax benefits, doctor interested in samples',
    productsPromoted: ['prod-001', 'prod-002'],
    companyId: 'comp-001',
  },
  {
    id: 'visit-002',
    type: 'doctor',
    mrId: 'user-002',
    mrName: 'Amit Sharma',
    doctorId: 'doc-003',
    doctorName: 'Dr. Ramesh Iyer',
    timestamp: `${formatDate(today)}T11:15:00Z`,
    coordinates: { lat: 19.0178, lng: 72.8478 },
    notes: 'Presented BoneStrong Plus, doctor placed order',
    productsPromoted: ['prod-003'],
    companyId: 'comp-001',
  },
  {
    id: 'visit-003',
    type: 'shop',
    mrId: 'user-002',
    mrName: 'Amit Sharma',
    shopId: 'shop-001',
    shopName: 'MedPlus Pharmacy',
    timestamp: `${formatDate(today)}T14:00:00Z`,
    coordinates: { lat: 19.1197, lng: 72.8464 },
    notes: 'Restocked inventory, collected payment',
    productsPromoted: ['prod-001', 'prod-002', 'prod-003'],
    companyId: 'comp-001',
  },
  {
    id: 'visit-004',
    type: 'doctor',
    mrId: 'user-003',
    mrName: 'Priya Patel',
    doctorId: 'doc-002',
    doctorName: 'Dr. Sunita Rao',
    timestamp: `${formatDate(today)}T10:00:00Z`,
    coordinates: { lat: 19.0596, lng: 72.8295 },
    notes: 'Discussed CardioMax clinical studies',
    productsPromoted: ['prod-001'],
    companyId: 'comp-001',
  },
  {
    id: 'visit-005',
    type: 'doctor',
    mrId: 'user-003',
    mrName: 'Priya Patel',
    doctorId: 'doc-004',
    doctorName: 'Dr. Kavita Shah',
    timestamp: `${formatDate(today)}T12:30:00Z`,
    coordinates: { lat: 19.1075, lng: 72.8263 },
    notes: 'Introduced SkinGlow Cream, provided samples',
    productsPromoted: ['prod-004'],
    companyId: 'comp-001',
  },
];

// Tasks
export const mockTasks: Task[] = [
  {
    id: 'task-001',
    mrId: 'user-002',
    mrName: 'Amit Sharma',
    type: 'doctor',
    doctorId: 'doc-006',
    doctorName: 'Dr. Meena Kulkarni',
    dueDate: `${formatDate(today)}T15:00:00Z`,
    notes: 'Present FemCare 250mg, discuss prescription patterns',
    status: 'pending',
    createdBy: 'user-001',
    companyId: 'comp-001',
  },
  {
    id: 'task-002',
    mrId: 'user-002',
    mrName: 'Amit Sharma',
    type: 'shop',
    shopId: 'shop-002',
    shopName: 'Apollo Pharmacy',
    dueDate: `${formatDate(today)}T17:00:00Z`,
    notes: 'Collect pending payment, check stock levels',
    status: 'pending',
    createdBy: 'user-001',
    companyId: 'comp-001',
  },
  {
    id: 'task-003',
    mrId: 'user-003',
    mrName: 'Priya Patel',
    type: 'doctor',
    doctorId: 'doc-005',
    doctorName: 'Dr. Prakash Desai',
    dueDate: `${formatDate(today)}T16:00:00Z`,
    notes: 'Introduce PediaVit Syrup, provide samples',
    status: 'pending',
    createdBy: 'user-001',
    companyId: 'comp-001',
  },
  {
    id: 'task-004',
    mrId: 'user-004',
    mrName: 'Vikram Singh',
    type: 'doctor',
    doctorId: 'doc-001',
    doctorName: 'Dr. Anil Mehta',
    dueDate: `${formatDate(today)}T10:00:00Z`,
    notes: 'Follow up on CardioMax order',
    status: 'completed',
    completedAt: `${formatDate(today)}T10:30:00Z`,
    visitId: 'visit-001',
    createdBy: 'user-001',
    companyId: 'comp-001',
  },
];

// Attendance
export const mockAttendance: Attendance[] = [
  {
    id: 'att-001',
    mrId: 'user-002',
    mrName: 'Amit Sharma',
    date: formatDate(today),
    firstPunch: `${formatDate(today)}T09:00:00Z`,
    lastPunch: `${formatDate(today)}T14:30:00Z`,
    totalVisits: 3,
    status: 'present',
    route: [
      { timestamp: `${formatDate(today)}T09:00:00Z`, coordinates: { lat: 19.0760, lng: 72.8777 }, type: 'punch', label: 'Start' },
      { timestamp: `${formatDate(today)}T09:30:00Z`, coordinates: { lat: 19.1364, lng: 72.8296 }, type: 'visit', label: 'Dr. Anil Mehta' },
      { timestamp: `${formatDate(today)}T11:15:00Z`, coordinates: { lat: 19.0178, lng: 72.8478 }, type: 'visit', label: 'Dr. Ramesh Iyer' },
      { timestamp: `${formatDate(today)}T14:00:00Z`, coordinates: { lat: 19.1197, lng: 72.8464 }, type: 'visit', label: 'MedPlus Pharmacy' },
      { timestamp: `${formatDate(today)}T14:30:00Z`, coordinates: { lat: 19.0760, lng: 72.8777 }, type: 'punch', label: 'End' },
    ],
    companyId: 'comp-001',
  },
  {
    id: 'att-002',
    mrId: 'user-003',
    mrName: 'Priya Patel',
    date: formatDate(today),
    firstPunch: `${formatDate(today)}T09:30:00Z`,
    lastPunch: `${formatDate(today)}T13:00:00Z`,
    totalVisits: 2,
    status: 'present',
    route: [
      { timestamp: `${formatDate(today)}T09:30:00Z`, coordinates: { lat: 19.0596, lng: 72.8295 }, type: 'punch', label: 'Start' },
      { timestamp: `${formatDate(today)}T10:00:00Z`, coordinates: { lat: 19.0596, lng: 72.8295 }, type: 'visit', label: 'Dr. Sunita Rao' },
      { timestamp: `${formatDate(today)}T12:30:00Z`, coordinates: { lat: 19.1075, lng: 72.8263 }, type: 'visit', label: 'Dr. Kavita Shah' },
      { timestamp: `${formatDate(today)}T13:00:00Z`, coordinates: { lat: 19.0596, lng: 72.8295 }, type: 'punch', label: 'End' },
    ],
    companyId: 'comp-001',
  },
  {
    id: 'att-003',
    mrId: 'user-004',
    mrName: 'Vikram Singh',
    date: formatDate(today),
    firstPunch: `${formatDate(today)}T08:45:00Z`,
    totalVisits: 4,
    status: 'present',
    route: [
      { timestamp: `${formatDate(today)}T08:45:00Z`, coordinates: { lat: 19.2183, lng: 72.9781 }, type: 'punch', label: 'Start' },
    ],
    companyId: 'comp-001',
  },
  {
    id: 'att-004',
    mrId: 'user-005',
    mrName: 'Neha Gupta',
    date: formatDate(today),
    status: 'absent',
    totalVisits: 0,
    route: [],
    companyId: 'comp-001',
  },
];

// Daily Explanations
export const mockExplanations: DailyExplanation[] = [
  {
    id: 'exp-001',
    mrId: 'user-003',
    mrName: 'Priya Patel',
    date: formatDate(today),
    reason: 'fewer_visits',
    reasonCategory: 'fewer_visits',
    notes: 'Had to leave early due to family emergency. Will cover remaining doctors tomorrow.',
    status: 'pending',
    companyId: 'comp-001',
  },
  {
    id: 'exp-002',
    mrId: 'user-005',
    mrName: 'Neha Gupta',
    date: formatDate(today),
    reason: 'other',
    reasonCategory: 'other',
    notes: 'Unwell, took sick leave. Medical certificate attached.',
    status: 'approved',
    approvedBy: 'user-001',
    approvedAt: `${formatDate(today)}T10:00:00Z`,
    companyId: 'comp-001',
  },
];

// Expenses
export const mockExpenses: Expense[] = [
  {
    id: 'exp-001',
    mrId: 'user-002',
    mrName: 'Amit Sharma',
    date: formatDate(today),
    dailyFare: 350,
    hqAllowance: 200,
    otherExpenses: 0,
    notes: 'Local travel by auto',
    status: 'pending',
    companyId: 'comp-001',
  },
  {
    id: 'exp-002',
    mrId: 'user-003',
    mrName: 'Priya Patel',
    date: formatDate(today),
    dailyFare: 280,
    hqAllowance: 200,
    otherExpenses: 50,
    notes: 'Parking charges at hospital',
    status: 'approved',
    approvedBy: 'user-001',
    approvedAt: `${formatDate(today)}T11:00:00Z`,
    companyId: 'comp-001',
  },
];

// Dashboard Metrics
export const mockAdminDashboardMetrics: DashboardMetrics = {
  totalVisitsToday: 12,
  attendancePercentage: 75,
  activeMRs: 3,
  totalMRs: 4,
  doctorsCovered: 5,
  shopsCovered: 2,
  pendingTasks: 3,
  pendingApprovals: 2,
};

export const mockMRDashboardMetrics: MRDashboardMetrics = {
  assignedTasks: 2,
  completedVisits: 3,
  pendingApprovals: 1,
  todaysRoute: mockVisits.filter(v => v.mrId === 'user-002'),
};

// Chart Data
export const mockVisitChartData: ChartDataPoint[] = [
  { date: '2024-12-30', value: 18, label: 'Mon' },
  { date: '2024-12-31', value: 22, label: 'Tue' },
  { date: '2025-01-01', value: 8, label: 'Wed' },
  { date: '2025-01-02', value: 25, label: 'Thu' },
  { date: '2025-01-03', value: 20, label: 'Fri' },
  { date: '2025-01-04', value: 15, label: 'Sat' },
  { date: '2025-01-05', value: 12, label: 'Sun' },
];

export const mockMRComparisonData = [
  { name: 'Amit Sharma', visits: 45, target: 50 },
  { name: 'Priya Patel', visits: 38, target: 50 },
  { name: 'Vikram Singh', visits: 52, target: 50 },
  { name: 'Neha Gupta', visits: 28, target: 50 },
];
